
package ensa.com.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Operateur", targetNamespace = "http://controller.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Operateur {


    /**
     * 
     * @param num
     * @param nom
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "FindOpByNameAndNum")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "FindOpByNameAndNum", targetNamespace = "http://controller.example.com/", className = "ensa.com.webservice.FindOpByNameAndNum")
    @ResponseWrapper(localName = "FindOpByNameAndNumResponse", targetNamespace = "http://controller.example.com/", className = "ensa.com.webservice.FindOpByNameAndNumResponse")
    @Action(input = "http://controller.example.com/Operateur/FindOpByNameAndNumRequest", output = "http://controller.example.com/Operateur/FindOpByNameAndNumResponse")
    public boolean findOpByNameAndNum(
        @WebParam(name = "num", targetNamespace = "")
        int num,
        @WebParam(name = "nom", targetNamespace = "")
        String nom);

}
