
package ensa.com.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OperateurControllerService", targetNamespace = "http://controller.example.com/", wsdlLocation = "http://localhost:8089/Operation?wsdl")
public class OperateurControllerService
    extends Service
{

    private final static URL OPERATEURCONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException OPERATEURCONTROLLERSERVICE_EXCEPTION;
    private final static QName OPERATEURCONTROLLERSERVICE_QNAME = new QName("http://controller.example.com/", "OperateurControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/Operation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPERATEURCONTROLLERSERVICE_WSDL_LOCATION = url;
        OPERATEURCONTROLLERSERVICE_EXCEPTION = e;
    }

    public OperateurControllerService() {
        super(__getWsdlLocation(), OPERATEURCONTROLLERSERVICE_QNAME);
    }

    public OperateurControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPERATEURCONTROLLERSERVICE_QNAME, features);
    }

    public OperateurControllerService(URL wsdlLocation) {
        super(wsdlLocation, OPERATEURCONTROLLERSERVICE_QNAME);
    }

    public OperateurControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPERATEURCONTROLLERSERVICE_QNAME, features);
    }

    public OperateurControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperateurControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Operateur
     */
    @WebEndpoint(name = "OperateurPort")
    public Operateur getOperateurPort() {
        return super.getPort(new QName("http://controller.example.com/", "OperateurPort"), Operateur.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Operateur
     */
    @WebEndpoint(name = "OperateurPort")
    public Operateur getOperateurPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.example.com/", "OperateurPort"), Operateur.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPERATEURCONTROLLERSERVICE_EXCEPTION!= null) {
            throw OPERATEURCONTROLLERSERVICE_EXCEPTION;
        }
        return OPERATEURCONTROLLERSERVICE_WSDL_LOCATION;
    }

}
